Component advance, add Polkadot.js to connect the pallet.
OAK-Foundation/quadratic-funding-webapp pull request #1
Opened 2021-05-14 16:39 UTC by AmazingBeerBelly

Home Page:
![image](https://user-images.githubusercontent.com/25864116/118301002-25ea8800-b515-11eb-90a0-04b44b0ad9a8.png)

Project Detail:
![image](https://user-images.githubusercontent.com/25864116/118301165-5af6da80-b515-11eb-9a1f-fcbc24358ea7.png)

2021-05-17 17:48 UTC, AmazingBeerBelly commented
添加了Round的选择：

![Kapture 2021-05-18 at 01 48 09](https://user-images.githubusercontent.com/25864116/118533837-21270d80-b77b-11eb-8119-e7f27b57729c.gif)

2021-05-17 18:51 UTC, chrisli30 commented
在根目录我先yarn，然后yarn next-dev会报错呢？是少了什么步骤吗？

```
yarn next-dev
yarn run v1.22.4
$ yarn workspace @superprops/next run dev
$ next
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ready - started server on http://localhost:3000
info  - Using external babel configuration from /Users/mikasa/Code/quadratic-funding-webapp/packages/landing/babel.config.js
event - compiled successfully
event - build page: /404
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/mikasa/Code/quadratic-funding-webapp/node_modules/@polkadot/api/index.js
require() of ES modules is not supported.
require() of /Users/mikasa/Code/quadratic-funding-webapp/node_modules/@polkadot/api/index.js from /Users/mikasa/Code/quadratic-funding-webapp/packages/landing/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
```
![image](https://user-images.githubusercontent.com/2616844/118541112-31e96c00-b706-11eb-851c-42b700f57501.png)

2021-05-20 05:49 UTC, chrisli30 requested changes

2021-05-20 05:49 UTC, chrisli30 commented on packages/landing/src/containers/AppModern/Navbar/index.js
> +          logoSrc="https://res.cloudinary.com/forgelab-io/image/upload/v1618793068/OAK/logo-horizontal.png"
![image](https://user-images.githubusercontent.com/2616844/118924406-e693b100-b8f1-11eb-9602-c3ae71f69358.png)
在初始的时候，这里需要跟oak-website一样用白色的logo，不是紫色的

2021-05-20 05:49 UTC, chrisli30 commented on packages/landing/src/common/components/FeatureBlock/index.js
> +            <Project project={project} Icon={Icon} />
![image](https://user-images.githubusercontent.com/2616844/118924760-61f56280-b8f2-11eb-9e05-000634ea7d9a.png)

页面元素不需要带Project这个词了，直接显示链上的信息

2021-05-20 05:49 UTC, chrisli30 commented on packages/landing/src/common/components/Contributors/index.js
> +      }
![image](https://user-images.githubusercontent.com/2616844/118924930-aa148500-b8f2-11eb-91a4-e8619985d444.png)
这个contributor是链上拿的还是hard code的？

2021-05-20 05:49 UTC, chrisli30 commented on packages/landing/src/common/components/Contributors/index.js
> +  contributions,
双击这个圆圈的地方，整块会变黑，这里需要处理下，disable双击？

![image](https://user-images.githubusercontent.com/2616844/118925049-df20d780-b8f2-11eb-88e2-62f90aa380ef.png)

2021-05-20 05:49 UTC, chrisli30 commented on packages/landing/src/common/components/Project/index.js
> +      <Link href={{ pathname: `/detail/${id}`, query: { rid: roundId } }}>
现在 #Round 1和#Round 2的内容全部一样了，是不是链上设置的数据不对？

2021-05-20 05:50 UTC, chrisli30 commented
@AmazingBeerBelly 还有Security tab里的issues都解决一下吧，看能不能自动fix
https://github.com/OAK-Foundation/quadratic-funding-webapp/security/dependabot

2021-05-21 02:06 UTC, chrisli30 approved these changes

2021-05-21 02:06 UTC, merged